# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor_name', models.CharField(max_length=30, null=True)),
                ('new_neighborlocation', models.CharField(max_length=30, null=True)),
                ('occupants_count', models.PositiveIntegerField(default=0)),
                ('admin_foreign_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
