# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('business_email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='neighbor',
            old_name='neighbor_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='neighbor',
            old_name='new_neighborlocation',
            new_name='name',
        ),
        migrations.AddField(
            model_name='business',
            name='jirani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbor'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
