# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0002_auto_20180525_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('id_no', models.CharField(max_length=60)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Business')),
                ('jirani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
