# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='health_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbor',
            name='police_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
